"""한국환경공단 AirKorea API용 Python 클라이언트."""

from airkorea._ratelimit import AsyncTokenBucket
from airkorea.catalog import (
    ApiCatalogEntry,
    ParamSpec,
    api_catalog,
    api_catalog_dicts,
    api_catalog_for_debug_input,
    api_catalog_for_method,
    api_catalog_params_for_method,
    get_api_catalog_entry,
)
from airkorea.client import SUPPORTED_ENDPOINTS, AirKoreaClient
from airkorea.codes import (
    AirQualityGrade,
    DataTerm,
    InformCode,
    Pollutant,
    SidoName,
    StatsDataGubun,
    StatsSearchCondition,
)
from airkorea.coords import (
    LatLon,
    LatLonLike,
    TmPoint,
    TmPointLike,
    coerce_latlon,
    coerce_tm_point,
    resolve_airkorea_tm,
    tm_to_wgs84,
    wgs84_to_tm,
)
from airkorea.debug import (
    DEBUGGABLE_METHODS,
    DEFAULT_ASSERTION,
    DebugRun,
    build_error,
    jsonable,
    load_debug_fixture,
    redact_sensitive,
    run_debug_method,
    save_debug_fixture,
    slugify,
)
from airkorea.exceptions import (
    AirKoreaAuthError,
    AirKoreaError,
    AirKoreaNetworkError,
    AirKoreaNoDataError,
    AirKoreaParseError,
    AirKoreaRateLimitError,
    AirKoreaRequestError,
    AirKoreaServerError,
)
from airkorea.metadata import (
    is_credential_param,
    load_env_value,
    load_service_key,
    make_cache_key,
    make_call_context,
    normalize_service_key,
    sanitize_request_params,
)
from airkorea.models import (
    AdvisoryOccurrence,
    AirKoreaCallContext,
    AirKoreaModel,
    AirKoreaPage,
    AirQualityMeasurement,
    AirQualityStat,
    BackgroundConcentration,
    CaiMeasurement,
    DustAlarm,
    EnglishAirQualityMeasurement,
    EnglishStation,
    ForecastNotice,
    HighPm25Forecast,
    NearbyStation,
    RawRecord,
    Station,
    TmCoordinate,
    TrafficStat,
    WeeklyForecastNotice,
)
from airkorea.pagination import (
    has_next_page,
    iter_paginated_pages,
    next_page_no,
)

__version__ = "0.4.0"
PROVIDER_NAME = "python-airkorea-api"

__all__ = [
    "AirKoreaAuthError",
    "AirKoreaCallContext",
    "AirKoreaClient",
    "AirKoreaError",
    "AirKoreaNetworkError",
    "AirKoreaNoDataError",
    "AirKoreaParseError",
    "AirKoreaPage",
    "AirKoreaRateLimitError",
    "AirKoreaRequestError",
    "AirKoreaServerError",
    "AirKoreaModel",
    "AirQualityGrade",
    "AirQualityMeasurement",
    "AirQualityStat",
    "ApiCatalogEntry",
    "AdvisoryOccurrence",
    "AsyncTokenBucket",
    "BackgroundConcentration",
    "CaiMeasurement",
    "DataTerm",
    "DEBUGGABLE_METHODS",
    "DEFAULT_ASSERTION",
    "DebugRun",
    "DustAlarm",
    "EnglishAirQualityMeasurement",
    "EnglishStation",
    "ForecastNotice",
    "HighPm25Forecast",
    "InformCode",
    "LatLon",
    "LatLonLike",
    "NearbyStation",
    "ParamSpec",
    "Pollutant",
    "PROVIDER_NAME",
    "RawRecord",
    "SidoName",
    "Station",
    "StatsDataGubun",
    "StatsSearchCondition",
    "SUPPORTED_ENDPOINTS",
    "TmCoordinate",
    "TmPoint",
    "TmPointLike",
    "TrafficStat",
    "WeeklyForecastNotice",
    "__version__",
    "api_catalog",
    "api_catalog_dicts",
    "api_catalog_for_debug_input",
    "api_catalog_for_method",
    "api_catalog_params_for_method",
    "build_error",
    "coerce_latlon",
    "coerce_tm_point",
    "get_api_catalog_entry",
    "has_next_page",
    "is_credential_param",
    "iter_paginated_pages",
    "jsonable",
    "load_debug_fixture",
    "load_env_value",
    "load_service_key",
    "make_cache_key",
    "make_call_context",
    "next_page_no",
    "normalize_service_key",
    "redact_sensitive",
    "resolve_airkorea_tm",
    "run_debug_method",
    "save_debug_fixture",
    "sanitize_request_params",
    "slugify",
    "tm_to_wgs84",
    "wgs84_to_tm",
]
